config-version: 2
name: 'ga4_export'
version: '0.2.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  ga4_export:
    +schema: ga4_export
    +materialized: table
    staging:
      +schema: stg_ga4_export
      +materialized: view

vars:
  ga4_export:
    event_table: "{{ source('ga4_export', 'event') }}"
    key_events: []