name: 'ga4_export_integration_tests'
version: '0.2.0'
config-version: 2
profile: 'integration_tests'

models:
  ga4_export:
    +schema: "{{ 'ga4_export_sqlw_tests' if target.name == 'databricks-sql' else 'ga4_export' }}"
    # +schema: "ga4_export_{{ var('directed_schema','dev') }}" ## To be used for validation testing
    staging:
      +materialized: table

vars:
  ga4_export:
    ga4_export_schema: ga4_export_integration_tests_6
    ga4_export_event_identifier: "event_data"
    # key_events: ['purchase'] # use when testing the key_events variable and validation testing

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']


seeds:
  +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"
  ga4_export_integration_tests:
    +column_types:
      param_engagement_time_msec: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      stream_id: "{{ 'varchar(100)' if target.name in ('redshift', 'postgres') else 'string' }}"